API_VERSION = "/api/v3"
API_PATH = {
    "login" :           "/user/login",
    "getPost" :         "/post",
    "getCommunity" :    "/community",
    "listCommunities" : "/community/list",
    "listPosts" :       "/post/list",
    "submitPost" :      "/post",
    "editPost" :        "/post",
    "submitComment" :   "/comment",
    "likePost" :        "/post/like",
    "likeComment" :     "/comment/like",
    "followCommunity" : "/community/follow",
    "resolveObject":    "/resolve_object",
    "search":           "/search",
    "getSite":          "/site",
    "leaveAdmin":       "/user/leave_admin",
    "register":         "/user/register",
    "getPersonDetails": "/user",
    "getPersonMentions": "/user/mention",
    "markPersonMentionAsRead", "/user/mention/mark_as_read",
    "getReplies":       "/user/replies",
    "banPerson":        "/user/ban",
    "getBannedPersons": "/user/banned",
    "blockUser":        "/user/block",
    "deleteAccount":    "/user/delete_account",
    "passwordReset":    "/user/password_reset",
    "passwordChangeAfterReset": "/user/password_change",
    "saveUserSettings": "/user/save_user_settings",
    "markAllAsRead": "/user/mark_all_as_read",
    "saveUserSettings": "/user/save_user_settings",
    "changePassword": "/user/change_password",
    
}
